# Generated by Django 3.0 on 2022-01-31 13:24

from django.apps import apps as global_apps
from django.db import migrations

# source : https://docs.djangoproject.com/fr/4.0/howto/writing-migrations/#migrating-data-between-third-party-apps


def import_content_from_old_app(apps, schema_editor):
    try:
        profile_oc_lettings_site = apps.get_model('oc_lettings_site', 'Profile')
    except LookupError:
        # The old app isn't installed.
        return

    profile_lettings_app = apps.get_model('profiles', 'Profile')
    user_project = apps.get_model('auth', 'User')

    profile_lettings_app.objects.bulk_create(
        profile_lettings_app(user=user_project.objects.get(pk=old_profile.user.id),
                             favorite_city=old_profile.favorite_city)
        for old_profile in profile_oc_lettings_site.objects.all()
    )


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(import_content_from_old_app, migrations.RunPython.noop),
    ]

    if global_apps.is_installed('oc_lettings_site'):
        dependencies.append(('oc_lettings_site', '0001_initial'))

