# Generated by Django 3.0 on 2022-01-29 20:51
from django.apps import apps as global_apps
from django.db import migrations


def import_content_from_old_app(apps, schema_editor):

    try:
        letting_oc_lettings_site = apps.get_model('oc_lettings_site', 'Letting')
    except LookupError:
        # The old app isn't installed.
        return
    # dans les migrations, l'accès à object via l'import de la classe n'est pas possible
    # il faut passer par apps.get model, puis lui appliquer le "objects.get" classique
    letting_lettings_app = apps.get_model('lettings', 'Letting')
    address_lettings_app = apps.get_model('lettings', 'Address')

    letting_lettings_app.objects.bulk_create(
        letting_lettings_app(id=old_lettings.id, title=old_lettings.title,
                             address=address_lettings_app.objects.get(pk=old_lettings.address.id))
        for old_lettings in letting_oc_lettings_site.objects.all()
    )


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0001_initial'),
        ('lettings', '0002_auto_20220128_1730'),
    ]

    operations = [
        migrations.RunPython(import_content_from_old_app, migrations.RunPython.noop),
    ]

    if global_apps.is_installed('oc_lettings_site'):
        dependencies.append(('oc_lettings_site', '0001_initial'))
