version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  main:
    jobs:
      - build-test
      - containerization:
          requires:
            - build-test
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - containerization
          filters:
            branches:
              only: main


jobs:
  build-test:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
  containerization:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Docker image to DockerHub
          command: |
            docker build -t $DOCKERHUB_USERNAME/oc-lettings:$CIRCLE_SHA1 .
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/oc-lettings-lettings:$CIRCLE_SHA1
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Build, push and deploy Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a oc-lettings-15 web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a oc-lettings-15 web